---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: levyos
# description will be included in the image's metadata
description: levyOS

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: fonts
    fonts:
      nerd-fonts:
        - Hack

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: justfiles
    validate: true
    install: true
    include:
      - levyos-setup-reboot-to-windows.just
      - levyos-setup-virtualization.just

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        repo:
          title: Flathub (system)
        install: # system flatpaks we want all users to have and not remove
          - io.github.Qalculate
          - org.libreoffice.LibreOffice
          - org.mozilla.firefox
#      - scope: user # Also add Flathub user repo, but no user packages
#        repo:
          # you can override the title to make inclusion of both system and user repos clearer
#          title: Flathub (user)

  - type: dnf
#    repos:
#      copr:
#        - atim/starship
    install:
      packages:
        - 7zip
        - alacritty
        - eza
        - fastfetch
        - fish
        - podman-compose
        - rclone
        - virt-install
        - virt-manager
        - libvirt-daemon-config-network
        - libvirt-daemon-kvm
        - qemu-kvm
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
